# Generated by Django 4.2.7 on 2023-11-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HMavsum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hovirgi_mavsum', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Hozirgi Mavsum',
                'verbose_name_plural': 'Hozirgi Mavsum',
            },
        ),
    ]
